# 범위결정과 핵심질문

## 범위결정

- Population: Adult with frequent and/or moderate-to-severe episodic migraine

- Intervention: Drug 
    - Anti-epileptic drug
    - Beta blocker/CCB/ARB/ACE 
    - Anti-Depressant
    
- Professional: 
    - Primary care physician, Nurse, and healthcare professionals 
    
- Outcome: The frequency of migraine prevention drug prescription as suggested 

- Healthcare setting: Primary care setting in Korea

## Key Questions

1. Episodic migraine환자에서 예방치료를 고려해야 하는 요인들(두통빈도, 두 통강도, 환자의 선호도, ADL에 대한 영향 등)은 무엇인가?

2. 예방치료를 진행중인 episodic migraine환자에서 치료의 중단은 어떻게 결 정해야 하는가?

3. Episodic migraine환자에서 예방치료로 베타차단제(beta blocker: propranolol 등)를 사용하는 것이 타약제, 위약 또는 치료하지 않는 것에 비해 두통의 완화에 효과적인가?

4. Episodic migraine환자에서 예방치료로 칼슘채널차단제(calcium channel blocker: flunarizine 등)를 사용하는 것이 타약제, 위약 또는 치료하지 않는 것에 비해 두통의 완화에 효과적인가?

5. Episodic migraine환자에서 예방치료로 안지오텐신전환효소억제제(angiotensin converting enzyme inhibitor)나 안지오텐신수용체차단제(angiotensin receptor blocker: candesartan 등)를 사용하는 것이 타약제, 위약 또는 치료 하지 않는 것에 비해 두통의 완화에 효과적인가?

6. Episodic migraine환자에서 예방치료로 항우울제(anti-depressant: amitryptiline 등)를 사용하는 것이 타약제, 위약 또는 치료하지 않는 것에 비해 두통의 완화에 효과적인가?

7. Episodic migraine환자에서 예방치료로 항경련제(anti-epileptic agent: divalproex sodium, sodium valproate, topiramate 등)를 사용하는 것이 타약제, 위약 또는 치료하지 않는 것에 비해 두통의 완화에 효과적인가?

## Drugs

- Beta blocker

    - propranolol 
    - Metoprolol 
    - Timolol
    - Atenolol
    - Nadolol 
    - Nebivolol 
    - Pindolol
    

- Calcium channel blocker

    - flunarizine 
    - cinnarizine 
    - verapamil 
    - nicardipine
    

- angiotensin converting enzyme inhibitor or angiotensin receptor blocker

    - Lisinopril
    - candesartan
    

- anti-depressant

    - amitryptiline 
    - nortriptyline 
    - Venlafaxine 
    - Fluoxetine
    

- anti-epileptic agent

    - divalproex sodium 
    - sodium valproate 
    - topiramate
    - Carbamazepine
    - Gabapentin
